[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
lib_deps = https://github.com/FastLED/FastLED.git
    https://github.com/andriii-droid/Button.git

monitor_speed = 115200
